name: 📋 Task
description: Create a development task
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What needs to be achieved?
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
        - [ ] ...